language: python
python:
- '2.7'
install:
- pip install ansible>=2.4.0 molecule apache-libcloud pycrypto
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: MSL8q7q/PYZd6Jf1eAVQfAeKSq+/IeCqs6vvQK+2oqp4sn25MIJ21Co4Zdvw8CbWpUorM6VOd7K3cB1KxvTXPFiIa4Hs+LlOq38GBteKHmB0COWeh7hOZ6IQadmW40NUrbnOJH7LqEj3uA+mUf/RpWBcK3XvhWp32qi8ptjX0TMxVC2b+/AmjBsDN1H3bzpyY0gHZqV7fe4RjGkr6z/whyEgj753jMCFTnm/5BmdAsCOBavUEHEl+1SewUuBL149z9At9v3LZiH0yhkylqFYPEj8dXxB4bU3I5YNfliEY3UxVJl7s+T/1obDgr5vy3iO0Xv+IvUsKANeezHcC0glZVFam4UhnuVAaack37zt/NqUCHdRW72RCfGHMjDcqDxXJSBKu93toGGI7u4LT632IrjjSduBRU+G8DMWOkZHsOXJ+dtyohyFHYBBMq5Mx98rAa+Mx21Q8caUHKzkgGq1e8TZTNf5uqHsQ3rJS0HcvHo+ynNhCiTEECgqySq+HDCc+O0z0MRYVkM+08sVQ5foyxLkmxHeaUZdpm2fq747WjP1wmVlc7nYgz9J1vkRvIpL72aLwQxBvcSruxvCOLOGiGLM+c7GLJ3gkFK/2LYbBxhgbYVLN0rDxhQN625rmdlXt8obdRz+t6ffBG3hlZtgh33z5WMyq4XmCJxD0otlX7k=
  - secure: IPwc69WXg5wjrANbFcwIw3vW+k212rD7VP1DAAh+7x/0cgpyP8ueOrVHnrRqs2zBoaS4SYPpVSSD+ae0lKE7AJ7NAUiW3Xl5vY7xkKyE2nImWhqiXLbevqsevnceZyOppOAFBSu4cDBhFMhzK/pFE/1aivff+LGRRR5TMkQ/qK42c9N5aELFXBI592Hm45GLx1RL86sDWjVZDZ09MqRa3xkAjPBmulDQyTo8Mz6lMKXgxj6znrqeI+tZb7pa2EUBioXDJSB0VfRVZTzubOkREvBxUQgpnzACHWXqA8n8dcymIwP8Q7+Wc333u+MaYHjFEu0a6CKX72uWyApajou3gnyA/NMvzxsr0zRefJLl6X0z4GYm/ScqAHk1ebmTPwMpTFeyO4E7BCATCE11tRyGW8cWkUdkzl36dQy5LA5/zzIVeSysVRxlfb/OCpadkpzzpEopjHa9xDvGg5S5QK/IvSsRbZwebdCDNzAOKSAdYqELxkN63LKrLmoD4mh0Y6s+Ldnwv/RZpJFJ1r6Wc7+6ILRNjMfC0MK47tGz0i/x5BaRGk40ZyLUjvzouyKD6etT46uCCSLlGmdB/UlWBy99qnmjYnnmnRcb+rmKZExhzmKdvhsv8WVSRvrwsLQeebL0ctNDLt5L7wyPhDx8gov1skETzN3fhhKPKtxfqHJ8X10=
  - secure: lEmqcqATvdrSp/hZOggKS0bO+EJDTpyI/tRDt65BGQ/NkyBzudmTiu3VF6rYrphMRQlN36naxaeHd1z5sqjoQr7qAiaing/iFa5AXaXNFuPR1VfsSeOv4S3z17Cvsx4Wr0fb+POGeHdzr/ENXFs1chYudld7OAUgupcaw7IMu208Go9YnRuAdgS3iNg7hUsbR0feu5/84ffPlQ1lToE7EnNpzh30n/HjjrhgsDNnGMF7Ny6ELO6yNEl361FWL+zlWZtvxixGfnA/7xgtiBmlhNDpSF9Et+GWEcuiO9INzPrbg2dboIq0obHpoed+LDcDnkgT3nruZ9nLmUICcuSDyRlhwXsm5CmpIxkCNhBj3NnV4EE6ip8EriXJiIzNLtp3XETjnsUjX8+Ks8JHxBU1ZEQJ+WTsyqLIHWnI6aMVdv7fnBhB5vFsSRB+wEXbJQYfl9q5TzczNIkDvovgv4Kk6Zz6FeGTxnU7NJZdQ1L5O8yj5s67pM6ItZ5HhSmE6qon4gUdppvz+E/58IN8TGMG/pHJFMg0e2XjLxqM8w5v+agl37z8yg3qcEpnfIF2hIeqOe44n1R9fvHcniRhRjLrDbtD0p54XCpVeM+bqirg5wI1UDFeCwOXwbMKhGJw3GSktz1lx5eqR4zraudM6AUK5Hxrx2p5f+nXy4GHl1Q6MtM=
script:
  - molecule create
  - molecule converge
  - molecule verify
after_script:
  - molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_394ce8f6455d_key -iv $encrypted_394ce8f6455d_iv -in secret.tar.enc -out secret.tar -d
- tar xvf secret.tar
- mv google_compute_engine ~/.ssh/
- chmod 0600 ~/.ssh/google_compute_engine

