language: python
python:
- '2.7'
install:
- pip install ansible>=2.4.0 molecule apache-libcloud pycrypto
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: HEa9jdIWfQWysY7JM5lUzfHtcIHILC7mWuoy6Hl4OzKxVQJNGOmUQo6h9dJZekDUN+BD0WpukUXWv9FekjsOYQM3bI6tYhqgDeH0h8SIrZl0xdnRndm4bbTRJMpnWVufhu0eBe5ZDtRQXNgHf4neJbdFzN1VHrawrmHbxKT36D46g7QkGQYN90iCX98IeW0wl3W7ZTHkP7+azkyW0TWUh1JUbRZIXPhyQv8cJRM3fgraVWgtsRotiPhwvnWlueWFwWeHI4aSeGbse0FHNUz7TeXfD+dfQUzEb43Lp5lNCtew16WiIvQOB911O5usIZNDoM5JFuSajqCCytYJAb8/cOD0ovc1Vhj5QPFupLpOPhQx5DokB/MPEOgxTzW3RgwRqejy6ZGZWozB1TWuwaLL5FbttJhVMUk/el70OzOYR/5DOx31bQ3RtJauQfycFaJGe3VjA9fa87fgF4Xs0riBiEwx5/NcFbobGeKW4nUf/Cqaxzyp2dZlC5bAlqn/LDySI9trx359sGDoSRzaG/ej3IKzrPmdBtDqlhEpPw79tbU8zOgtG3Ixb8Is85BXqdK0VuOBffViK+nwI72cIfU2Mh00GRBCMmgV5qnSW/zidbGQuDhoWbzk5KYe96U0kvTf7Ov0xuoBVesVzMd7+69Ql345P5G3qohB3B6UWfLmQZs=
  - secure: F6roXQgjkbKT+9o8TDnOgUkr1iJw8fn5nsOnptq8Og3G8lSF8JOdaWsUyGIaBAxpslEERjNC+vgv3I9ZPLYNP0MuXz9ut2nLnyxdHJSzf8f6Yjuwb/YM5fr+MLjhgiFgd4Fz1SXekZaSvT5a2kuOhy1NtL5bvWwYKEv6M+ZMN6mMvX3v9/QqnzH7R0bd7vpltdYlMshqJvZR9meNWXepW527Zf8lj4TttSv2HeviA6fe1FH8IL3Zx9VNWZDyzlLPsoRla1p9S+GQJa1HB3ghrWdTTsE9AmrZYZoKSNNVj2cqH/pLdIQuB1TbF0sxbyOq3JZPD1xOWjbN8vTw7A+oalU6/xDqhqZ8u5xCcvHi1T+uIc6OraA6358rXqAns7J+2nc/+fSa+6WZcNIiKB78kL3UFYX40C3kwASj81sSrOjbuoE8p7YJmjaHzjGfUq/8Fk/SAovx+9mPXQPRE4snGrxVqD9c5GjYCAj6RhQS4Owfm+W3pkvGK7OtmTEdBgY0KdXlG2GFU1uOAdEfHfQRkuquVboLx1CedU1TgIzSrq+Gjo27aLePoFv4RFfkj/P5fDA5fbcqBwv6GBvHVydPalyiwTW763DwZvMfbW7lYdCzenRjF5i+YzjisTdLGN0k4PsWtZsP3gHkOx22rd5ZkXDd2U1/aE6V5+Y6XW6gIkw=
  - secure: RsD7yfYZqNGEBfJ7F3TCgsmF1v+u0738oRvVsseUVJi8jKzdMDlMHKUU/a2Qk/xdk2eFjUQkgxYHJ++UCj5DGKThpJCREucbetnYFHMOjy0YRzKKw96qvZkCgAAvYdaQdfFqBNxmSBViEQxVbHoXNmhxt+dk/Ma2QhllZy1AWZPPJfGUkGExpL2lbFX2CzEaDF8zAsus3l2V9vyUf3kKKUKaT8p3xbKnfi8JV4obkcR5AR1LDpV2DmOHFIw3OCR3DyGSyYn2yTzv6dr9j1fsk4SuxcNnAUb1gqtMhQAQLqlLN5uN9pZT2PpxYPh9QaColaeeVci9mEsmZ2szZRNV1kPn+CmzBX6hcRpvmf6ou/w9yGvXjJaasnUFyZQ972NkEy1VplmFc2FjOu7DtvV1zXMetfAyAE4Ebvau1y06zFoEPPpxBx7b0JFWNfTjNieaFAEgc6IIlCtlhSbglE0p2Jhs85InkLblh75gs0hYK0jHStMRHmqzXp5FZ4jlxCeNoD5I908lCtPmNKwJbE1QJGG6ddqvtrN9wYY64JYBzHkGnZMUBTXNOIxesHObP3MXqEzaPM/q2588E4v7n8TO6j1BFKuvS8OIiuc/gqNOuwZ+Qh5oQXIUlTd99gTxHquTQZDNtbCFigPEFHLrPauVLzAWuoVrgGF21UZBv7NMa5Y=
script:
- molecule --debug create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_394ce8f6455d_key -iv $encrypted_394ce8f6455d_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine

