---
- name: Add key for custom repository
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EA312927
    state: present
  tags: install
- name: Add custom repository
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
    filename: mongo-org-3.2.list
  tags: install
- name: Install MongoDB apt
  apt:
    name: mongodb-org
    state: present
    update_cache: yes
  tags: install
- name: Autostart mongod daemon
  service:
    name: mongod
    enabled: yes
  tags: install
