---
# tasks file for db
- name: Show info about the environments this host belong to
  debug:
    msg: "This host is in {{ env }} environment!"

- include: install_mongo.yml
- include: config_mongo.yml

